URL = 'https://qauto2.forstudy.space/'
CREDENTIALS = {}

#todo 25XPATH AND 25CSS-SELECTORS

# XPATH - SELECTORS
print('''//button[@class="settings-control btn btn-secondary" and text()='km']''')
print('''//label[@for='passwordChangeOldPassword']/following-sibling::input[@type ='password']''')
print('''//button[@class='hero-descriptor_btn btn btn-primary' and text() = 'Sign up']''')
print('''//p[@class='about-block_descr lead' and text() = 'Keep track of your replacement schedule and plan your vehicle maintenance expenses in advance.']''')
print('''//div[@class='contacts_socials socials']/child::a/child::span[@class='socials_icon icon icon-facebook']''')
print('''//app-header//child::button[text() = 'Guest log in']''')
print('''//div[@class='user-nav show dropdown']//child::a[@href='/panel/garage']''')
print('''//div[@class ='modal-content']//label[@for='addCarModel']''')
print('''//div[@class ='modal-content']//label[@for='addCarModel']/following-sibling::select''')
print('''//div[@class='input-group-append']//child::div''')
print('''//div[@class='input-group-append']//preceding-sibling::input''')
print('''//app-signin-form//descendant::label[text()='Password']''')
print('''//app-signin-form//descendant::label[text()='Password']/following-sibling::input''')
print('''//div[@class="modal-footer d-flex justify-content-between"]/child::button[text()='Registration']''')
print('''//app-garage//child::div[@class='car_logo car-logo']/img[@src='https://qauto2.forstudy.space/public/images/brands/audi.png']''')
print('''//app-garage//child::div[@class='car_actions']''')
print('''//app-garage//child::div[@class='car_actions']/child::button[text()='Add fuel expense']''')
print('''//div[@class='modal-content']/app-edit-car-modal//button[text()='Remove car']''')
print('''//app-update-mileage-form/form/button[@type='submit' and text()='Update']''')
print('''//p[starts-with(@class, 'car_name')]''')
print('''//p[contains(text(), 'Audi')]''')
print('''//span[@class='update-mileage-form_icon icon icon-tachometer']''')
print('''//app-profile//div[@class='panel-page_content']''')
print('''//app-profile//div[@class='panel-page_content']//img[@src='https://qauto2.forstudy.space/public/images/users/default-user.png']''')
print('''//app-profile//div[@class='panel-page_content']//img[@src='https://qauto2.forstudy.space/public/images/users/default-user.png']/following-sibling::p[contains(text(), 'Filip')]''')

# CSS-SELECTORS

print('''button.settings-control.btn.btn-secondary''')
print('''label[for='passwordChangeOldPassword'] + input[type='password']''')
print('''button.hero-descriptor_btn.btn.btn-primary''')
print('''p.about-block_descr.lead''')
print('''div.contacts_socials.socials > a > span.socials_icon.icon.icon-facebook''')
print('''app-header button.btn-link''')
print('''div.user-nav.show.dropdown a[href='/panel/garage']''')
print('''div.modal-content label[for='addCarModel']''')
print('''div.modal-content label[for='addCarModel'] ~ select''')
print('''div.input-group-append > div''')
print('''input[name='miles']''')
print('''app-signin-form label[for='signinPassword']''')
print('''app-signin-form label[for='signinPassword'] ~ input''')
print('''div.modal-footer.d-flex.justify-content-between > button.btn-link''')
print('''app-garage div.car_logo.car-logo > img[src='https://qauto2.forstudy.space/public/images/brands/audi.png']''')
print('''app-garage div.car_actions''')
print('''app-garage div.car_actions > button.btn-success''')
print('''div.modal-content app-edit-car-modal button.btn-danger''')
print('''app-update-mileage-form > form > button[type='submit']''')
print('''p[class^='car_name']''')
print('''p.car_name''')
print('''span.update-mileage-form_icon.icon.icon-tachometer''')
print('''app-profile div.panel-page_content''')
print('''app-profile div.panel-page_content img[src='https://qauto2.forstudy.space/public/images/users/default-user.png']''')
print('''app-profile div.panel-page_content img[src='https://qauto2.forstudy.space/public/images/users/default-user.png'] ~ p''')